sonar.projectKey=otp-service
sonar.projectName=OTP Service
sonar.sources=.
sonar.exclusions=**/tests/**,**/__pycache__/**,Dockerfile,.github/**
sonar.python.version=3.12
sonar.python.coverage.reportPaths=coverage.xml
sonar.sourceEncoding=UTF-8
